### ISSUE TITLE
NCAAB Teams df Not Loading For 2021

### ISSUE THREAD

**Issue by heirjordan23** [roclark/sportsipy#558]
**Describe the bug**
Team stats are not being generated for the 2021 NCAAB season. The 2020 season loads, but obviously teams have changed since then and enough time has passed that 2021 stats should be populated, as it's on sports-reference.com.

**To Reproduce**
from sportsreference.ncaab.teams import Teams

team_data = Teams(year=2021)
teams_data = team_data.dataframes
teams_data

**Expected behavior**
The code should generate a dataframe for all NCCAB teams for the 2021 season thus far. 

This code works:
from sportsreference.ncaab.teams import Teams

team_data = Teams(year=2020)
teams_data = team_data.dataframes
teams_data

**Desktop (please complete the following information):**
 - Google Colaboratory
 - Sportsreference Version 0.5.2

**Additional context**
Receive the error:
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'

**Comment by andrewduffey** [comment]
This is likely due to teams not playing games yet. The Team dataframe does math on attributes without checking if they have valid values.

**Comment by heirjordan23** [comment]
Hm, but games have been played, and the table loads on the actual site...

**Comment by andrewduffey** [comment]
If you run this code below it will print the teams that haven't played yet.

```
for team in Teams(year=2021):
    # Teams that haven't played a game yet
    if team.games_played == 0:
        print(team.abbreviation)
```
As a temporary solution you could add something like this to your code.
```
def get_team_dataframes(year=2021):
    dataframes = []
    for team in Teams(year):
        if team.games_played != 0:
            dataframes.append(team.dataframe)
    return pd.concat(dataframes)
```

**Comment by heirjordan23** [comment]
Great! This works, thank you!
