### ISSUE TITLE
mlb.Boxscore no longer works as intended

### ISSUE THREAD

**Issue by John8640** [roclark/sportsipy#718]
I have a more complex data analysis problem I'm working on but for simplicity sake, I will use the example code below:

from sportsipy.mlb.boxscore import Boxscore
game = Boxscore('BOS201806070')
df = game.dataframe
print(df)

When I use the above code in order to get the boxscores of a game, I receive an empty DataFrame (output is none). This has been a problem for both NBA box scores and MLB boxscores for me. I have used sportsipy before and never had this issue. I recently updated to Spyder 5.1.5 on my Mac and I have made sure that sportsipy is installed properly. I'm not sure if this is simply a user error on my end or something with the package itself. This is my first post on Github, and I'm not really sure if I've provided the correct information or context. If there is anymore info I can provide, I'm more than happy :)

**Comment by jack11wagner** [comment]
I am experiencing this issue as well about 30 minutes ago I was able to get a Boxscore now all I am getting is 'None'
